/**
 * client_prover.js — Z.E.N.I.T.H. B2B Client SDK (Proof of Concept Prover)
 *
 * ARCHITECTURAL ROLE:
 *   This script runs entirely on the CLIENT SIDE (crypto exchange / bank / PSP).
 *   It embodies the "Local Proof Generation" principle:
 *
 *     The client NEVER sends their KYC data (secretData) to the middleware.
 *     Instead, they compute a Groth16 ZK proof LOCALLY, proving that their
 *     data satisfies the compliance predicate WITHOUT revealing what the data is.
 *
 *   This is the cryptographic equivalent of showing a bouncer a
 *   mathematical certificate that you're over 18, without showing your passport.
 *
 * SOLVING THE PRIVACY PARADOX AT THE CLIENT LAYER:
 *   Traditional compliance APIs (e.g., Chainalysis KYT, ComplyAdvantage) require
 *   you to upload customer data to a third-party SaaS. This creates:
 *     1. GDPR Article 44-49 cross-border data transfer issues
 *     2. Vendor lock-in and single-point-of-failure
 *     3. Customer data exposure to supply-chain attacks
 *
 *   With Z.E.N.I.T.H.:
 *     - secretData (KYC record hash) stays on the client's hardware
 *     - Only the mathematical proof [π_a, π_b, π_c] travels over the wire
 *     - The compliance predicate (secretData * threshold = result) is verified
 *       on-chain without the verifier ever learning secretData
 *
 * DEPENDENCIES:
 *   npm install snarkjs axios fs-extra
 *
 * USAGE:
 *   node client_prover.js
 *   node client_prover.js --sender "0xYourWallet" --receiver "0xDestWallet" --amount 5000
 */

"use strict";

const snarkjs = require("snarkjs");
const axios = require("axios");
const fs = require("fs");
const path = require("path");

// Configuration — in production, load from environment / secrets manager
const CONFIG = {
  // Z.E.N.I.T.H. middleware endpoint
  ZENITH_API_URL: process.env.ZENITH_API_URL || "http://localhost:8000",
  ZENITH_API_KEY: process.env.ZENITH_API_KEY || "dev-api-key-replace-in-production",

  // Paths to the compiled circuit artifacts (generated by 1)
  // These files remain on the client's infrastructure — never uploaded
  WASM_PATH: path.resolve(__dirname, "compliance_circuit_js/compliance_circuit.wasm"),
  ZKEY_PATH: path.resolve(__dirname, "compliance_circuit.zkey"),
  INPUT_PATH: path.resolve(__dirname, "input.json"),

  // B2B transaction parameters (in production: read from exchange order book)
  DEFAULT_SENDER:   process.env.SENDER_WALLET   || "Wallet_A_Exchange",
  DEFAULT_RECEIVER: process.env.RECEIVER_WALLET || "Wallet_B_Bank",
  DEFAULT_AMOUNT:   parseFloat(process.env.AMOUNT || "5000"),

  // Request timeout (proof generation can take 1-5s on low-end hardware)
  REQUEST_TIMEOUT_MS: 30_000,
};

// CLI Argument Parsing (minimal, no external dep)
function parseArgs() {
  const args = process.argv.slice(2);
  const parsed = {};
  for (let i = 0; i < args.length; i += 2) {
    if (args[i].startsWith("--") && args[i + 1]) {
      parsed[args[i].slice(2)] = args[i + 1];
    }
  }
  return {
    sender:   parsed.sender   || CONFIG.DEFAULT_SENDER,
    receiver: parsed.receiver || CONFIG.DEFAULT_RECEIVER,
    amount:   parseFloat(parsed.amount || CONFIG.DEFAULT_AMOUNT),
  };
}

// 1: Load Circuit Input

/**
 * loadCircuitInput — reads and validates the circuit input from input.json
 *
 * In production:
 *   - secretData would be derived from the customer's KYC record hash
 *     (e.g., SHA-256 of document hashes, stored in a HSM)
 *   - publicThreshold would be the current regulatory minimum from a
 *     compliance configuration service (updated by the compliance team)
 *
 * The input is kept as a plain JSON file for hackathon MVP simplicity.
 * Production systems should use environment-injected secrets.
 *
 * @returns {Object} Circuit input signals {secretData, publicThreshold}
 */
function loadCircuitInput() {
  if (!fs.existsSync(CONFIG.INPUT_PATH)) {
    throw new Error(
      `Circuit input not found at ${CONFIG.INPUT_PATH}. ` +
      "Ensure input.json exists from 1 setup."
    );
  }

  const raw = fs.readFileSync(CONFIG.INPUT_PATH, "utf-8");
  const input = JSON.parse(raw);

  // Validate required fields
  if (!input.secretData || !input.publicThreshold) {
    throw new Error("input.json must contain 'secretData' and 'publicThreshold' fields");
  }

  console.log(
    `[ZENITH-SDK] Loaded circuit input | ` +
    `threshold=${input.publicThreshold} | ` +
    `secretData=<REDACTED> (never logged)`
  );

  return input;
}

// 2: Local ZK Proof Generation

/**
 * generateZKProof — the cryptographic heart of the client SDK
 *
 * Executes snarkjs.groth16.fullProve(), which:
 *   1. Compiles the circuit input into a witness (internal signal assignments)
 *      using the compiled .wasm circuit
 *   2. Generates a Groth16 proof using the proving key (.zkey)
 *      The proving key encodes the circuit's constraint system and
 *      the powers-of-tau structured reference string (pot12_final.ptau)
 *
 * CRYPTOGRAPHIC GUARANTEE:
 *   The resulting proof (π_a, π_b, π_c) is a succinct argument that
 *   satisfies: result = secretData × publicThreshold
 *   WITHOUT revealing secretData. The verifier only learns:
 *     - result (the product, public signal)
 *     - publicThreshold (public input)
 *     - That secretData ∈ {valid field elements that produce this result}
 *
 * TIME COMPLEXITY: O(n log n) witness generation + O(1) Groth16 proving
 * (constant-time proof generation after witness is computed)
 *
 * @param {Object} circuitInput - {secretData, publicThreshold}
 * @returns {Promise<{proof: Object, publicSignals: string[]}>}
 */
async function generateZKProof(circuitInput) {
  console.log("[ZENITH-SDK] Starting local ZK proof generation...");
  console.log(`[ZENITH-SDK] WASM circuit: ${CONFIG.WASM_PATH}`);
  console.log(`[ZENITH-SDK] Proving key: ${CONFIG.ZKEY_PATH}`);

  // Validate circuit artifact files exist
  for (const [label, filePath] of [["WASM", CONFIG.WASM_PATH], ["ZKey", CONFIG.ZKEY_PATH]]) {
    if (!fs.existsSync(filePath)) {
      throw new Error(
        `${label} file not found at ${filePath}. ` +
        "Run 1 setup: npx snarkjs groth16 setup && snarkjs zkey contribute"
      );
    }
  }

  const startTime = Date.now();

  // fullProve = witness generation + proof generation in one call
  // This is the recommended production API (vs. separate prove() calls)
  const { proof, publicSignals } = await snarkjs.groth16.fullProve(
    circuitInput,
    CONFIG.WASM_PATH,
    CONFIG.ZKEY_PATH
  );

  const proofTimeMs = Date.now() - startTime;

  console.log(`[ZENITH-SDK] ✅ ZK Proof generated in ${proofTimeMs}ms`);
  console.log(`[ZENITH-SDK] Public signals: [${publicSignals.join(", ")}]`);
  console.log(`[ZENITH-SDK] Proof protocol: ${proof.protocol}`);

  return { proof, publicSignals };
}

// 3: Optional Local Proof Verification (sanity check before API call)

/**
 * verifyProofLocally — pre-flight verification using the verification key
 *
 * This is an OPTIONAL but RECOMMENDED step before submitting to the API.
 * It saves network round-trip and blockchain gas if the local proof is invalid
 * (which can happen if the circuit input doesn't satisfy the constraints).
 *
 * In production: skip this if latency is critical and proof generation
 * is trusted (e.g., running in a TEE / secure enclave).
 *
 * @param {Object} proof - Groth16 proof object
 * @param {string[]} publicSignals - Public signals array
 * @returns {Promise<boolean>}
 */
async function verifyProofLocally(proof, publicSignals) {
  const vKeyPath = path.resolve(__dirname, "verification_key.json");

  if (!fs.existsSync(vKeyPath)) {
    console.warn("[ZENITH-SDK] ⚠️ verification_key.json not found — skipping local verification");
    return true; // Proceed optimistically
  }

  const vKey = JSON.parse(fs.readFileSync(vKeyPath, "utf-8"));
  const isValid = await snarkjs.groth16.verify(vKey, publicSignals, proof);

  if (isValid) {
    console.log("[ZENITH-SDK] ✅ Local proof verification passed");
  } else {
    console.error("[ZENITH-SDK] ❌ Local proof verification FAILED — will not submit to API");
  }

  return isValid;
}

// 4: Submit to Z.E.N.I.T.H. Middleware API

/**
 * submitComplianceRequest — sends proof + transaction intent to the middleware
 *
 * The payload design is intentional:
 *   - zk_proof: contains only the proof parameters (no witness data)
 *   - public_signals: the public outputs of the circuit (result + threshold)
 *   - sender/receiver/amount: transaction metadata for TGN graph construction
 *
 * The middleware NEVER receives secretData. The proof is a black box
 * that says "this secretData was valid" without revealing what it was.
 *
 * @param {string} senderWallet
 * @param {string} receiverWallet
 * @param {number} amount
 * @param {Object} proof - Groth16 proof from snarkjs
 * @param {string[]} publicSignals
 * @returns {Promise<Object>} API response with TX hash + certificate
 */
async function submitComplianceRequest(senderWallet, receiverWallet, amount, proof, publicSignals) {
  // Use amount in small units to avoid integer overflow in the API
  // 1 token = 1000 units for demo (avoids 1e18 wei overflow in Python int parsing)
  const amountWei = Math.floor(amount * 1000);

  // snarkjs returns pi_a/pi_c as [x, y, "1"] (3 elements) and pi_b as [[x1,x2],[y1,y2],["1","0"]]
  // We slice to [x, y] and [[x1,x2],[y1,y2]] to match our Pydantic model (2-element G1/G2 points)
  const payload = {
    sender_wallet: senderWallet,
    receiver_wallet: receiverWallet,
    amount: amount,
    amount_wei: amountWei,
    zk_proof: {
      pi_a: proof.pi_a.slice(0, 2),
      pi_b: proof.pi_b.slice(0, 2).map(row => row.slice(0, 2)),
      pi_c: proof.pi_c.slice(0, 2),
      protocol: proof.protocol,
    },
    public_signals: publicSignals,
    transaction_metadata: {
      purpose_code: "TRADE_SETTLEMENT",
      corridor: "cross_border",
      client_sdk_version: "2.0.0",
      submitted_at: new Date().toISOString(),
    },
  };

  console.log("\n[ZENITH-SDK] Submitting compliance request to middleware...");
  console.log(`[ZENITH-SDK] Endpoint: ${CONFIG.ZENITH_API_URL}/api/v1/compliance-check`);
  console.log(`[ZENITH-SDK] Sender: ${senderWallet}`);
  console.log(`[ZENITH-SDK] Receiver: ${receiverWallet}`);
  console.log(`[ZENITH-SDK] Amount: ${amount} tokens`);

  const response = await axios.post(
    `${CONFIG.ZENITH_API_URL}/api/v1/compliance-check`,
    payload,
    {
      headers: {
        "Content-Type": "application/json",
        "X-API-Key": CONFIG.ZENITH_API_KEY,
        "X-Client-SDK": "zenith-b2b-sdk/2.0.0",
        "X-Request-ID": `client-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`,
      },
      timeout: CONFIG.REQUEST_TIMEOUT_MS,
    }
  );

  return response.data;
}

// 5: Process and Display Result

/**
 * displayResult — human-readable compliance result output
 *
 * In production: this would feed into:
 *   - The exchange's compliance dashboard
 *   - An audit log (immutable, append-only)
 *   - Regulatory reporting pipeline (SWIFT MT199 / ISO 20022 pacs.008)
 */
function displayResult(result) {
  console.log("\n" + "=".repeat(70));
  console.log("Z.E.N.I.T.H. COMPLIANCE RESULT");
  console.log("=".repeat(70));

  const statusEmoji = {
    "APPROVED": "✅",
    "REJECTED_ZK": "❌",
    "REJECTED_TGN": "🚨",
    "BLOCKCHAIN_ERROR": "⚠️",
  };

  console.log(`Status:          ${statusEmoji[result.status] || "?"} ${result.status}`);
  console.log(`Request ID:      ${result.request_id}`);
  console.log(`Timestamp:       ${result.compliance_timestamp}`);

  if (result.transaction_hash) {
    console.log(`Transaction Hash: ${result.transaction_hash}`);
  }

  if (result.certificate_id) {
    console.log(`Certificate ID:  ${result.certificate_id}`);
    console.log(`                 (On-chain compliance audit trail — submit to regulator)`);
  }

  console.log("\n--- TGN Behavioral Analysis ---");
  const tgn = result.tgn_analysis;
  console.log(`Risk Score:      ${tgn.risk_score}/100 (${tgn.risk_level})`);
  console.log(`Reasoning:       ${tgn.reasoning}`);

  if (tgn.anomaly_flags && tgn.anomaly_flags.length > 0) {
    console.log("\n⚠️  Anomaly Flags:");
    tgn.anomaly_flags.forEach((flag, i) => {
      console.log(`  ${i + 1}. ${flag}`);
    });
  } else {
    console.log("Anomaly Flags:   None detected");
  }

  console.log("\n--- Graph Metrics ---");
  const gm = tgn.graph_metrics;
  console.log(`Graph size:      ${gm.nodes} nodes, ${gm.edges} edges`);

  console.log("=".repeat(70) + "\n");
}

// Main Orchestration

async function main() {
  const { sender, receiver, amount } = parseArgs();

  console.log("\n🔵 Z.E.N.I.T.H. Client SDK v2.0.0 — Initializing...\n");

  try {
    // Step 1: Load circuit inputs (secretData stays local)
    const circuitInput = loadCircuitInput();

    // Step 2: Generate ZK proof locally
    const { proof, publicSignals } = await generateZKProof(circuitInput);

    // Step 3: Optional local verification (saves API round-trip on invalid proofs)
    const localVerification = await verifyProofLocally(proof, publicSignals);
    if (!localVerification) {
      console.error("[ZENITH-SDK] Aborting — proof failed local verification");
      process.exit(1);
    }

    // Step 4: Submit to Z.E.N.I.T.H. middleware
    const result = await submitComplianceRequest(
      sender,
      receiver,
      amount,
      proof,
      publicSignals
    );

    // Step 5: Display result
    displayResult(result);

    // Exit code signals pipeline success/failure for CI/CD integration
    process.exit(result.status === "APPROVED" ? 0 : 1);

  } catch (error) {
    if (error.response) {
      // API returned an error response
      console.error("[ZENITH-SDK] ❌ API Error:", error.response.status, error.response.data);
    } else if (error.request) {
      // Network error — middleware unreachable
      console.error("[ZENITH-SDK] ❌ Network Error: Middleware unreachable at", CONFIG.ZENITH_API_URL);
      console.error("  → Ensure zenith_middleware.py is running: uvicorn zenith_middleware:app --port 8000");
    } else {
      // Local error (proof generation, file I/O, etc.)
      console.error("[ZENITH-SDK] ❌ Error:", error.message);
    }

    if (process.env.NODE_ENV === "development") {
      console.error(error.stack);
    }

    process.exit(2);
  }
}

// Run
main();